name: Monitor and Download File

on:
  schedule:
    # 每小时运行一次
    - cron: '0 * * * *'
  # 保留手动触发选项
  workflow_dispatch:

jobs:
  check-and-download:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and extract file
        run: |
          # 创建临时目录
          mkdir -p temp
          cd temp
          
          # 下载文件 (使用 -N 参数，只在文件更新时才下载)
          wget -N --no-check-certificate "https://jihulab.com/fourd/FourD/-/raw/main/local/单线路.zip" -O file.zip
          
          if [ -f file.zip ]; then
            # 解压文件到项目根目录，强制覆盖现有文件
            unzip -o file.zip -d ../
            echo "文件已更新并解压"
          else
            echo "文件下载失败或未发生更改"
            exit 1
          fi
          
          # 清理临时文件
          cd ..
          rm -rf temp

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # 检查是否有变更
          if git status --porcelain | grep .; then
            git add .
            git commit -m "Update files from jihulab (Automated)"
            git push
            echo "变更已提交并推送"
          else
            echo "没有检测到文件变更"
          fi

      - name: Check workflow status
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "工作流程成功完成"
          else
            echo "工作流程执行出现错误"
          fi
