name: Update URLs

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发
  push:
    paths:
      - 'TVBoxOSC/tvbox/api.json'
      - 'url.py'
      - 'requirements.txt'

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史以确保正确的git操作

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Show workspace structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Checking for requirements.txt:"
          if [ -f "requirements.txt" ]; then
            echo "requirements.txt found"
            cat requirements.txt
          else
            echo "requirements.txt not found"
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "Installing basic requirements..."
            pip install requests urllib3
          fi

      - name: Run URL update script
        run: |
          echo "Starting URL update process..."
          python url.py
          echo "After script execution:"
          ls -la
          if [ -f url.json ]; then
            echo "url.json was created successfully:"
            cat url.json
          else
            echo "Error: url.json was not created!"
            exit 1
          fi

      - name: Check for changes
        id: check_changes
        run: |
          if [ -f url.json ]; then
            if git diff --quiet url.json; then
              echo "No changes in url.json"
            else
              echo "has_changes=true" >> $GITHUB_OUTPUT
              echo "Changes detected in url.json"
            fi
          else
            echo "Error: url.json does not exist!"
            exit 1
          fi

      - name: Commit and push if changed
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add url.json
          git commit -m "Auto Update URLs: $(date -u '+%Y-%m-%d %H:%M:%S')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: url-json
          path: url.json
          if-no-files-found: error
